
plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist

# Website
url: https://jessedc.dev
name: An Internet of things
title: An Internet of things
description: Musings on iOS and PHP development, IoT and other bits and pieces
author: Jesse Collis
contact_url: http://about.me/jessedc

# Social profiles
linkedin_url: https://www.linkedin.com/in/jessedc/
github_url: https://github.com/jessedc

permalink: /:year/:month/:title/
atom_feed: /feed.xml

# Pagination
paginate: 10

# Stackoverflow
stackoverflow_user_name: jessedc
stackoverflow_user_id: 184130

# Github repositories
github_user: jessedc
github_repo_count: 6
github_show_profile_link: true
github_skip_forks: true

exclude:
- CLAUDE.md
- Gemfile
- Gemfile.lock
- README.md
