
plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist

# Website
url: https://blog.jcmultimedia.com.au
name: An Internet of things
title: An Internet of things
description: Musings on iOS and PHP development, IOT and other bits and pieces
author: Jesse Collis
contact_url: http://about.me/jessedc

permalink: /:year/:month/:title/
atom_feed: /feed.xml

# Pagination
paginate: 5

# Disqus Comments
disqus_short_name: jessedc
disqus_show_comment_count: false

# Stackoverflow
stackoverflow_user_name: jessedc
stackoverflow_user_id: 184130

# Github repositories
github_user: jessedc
github_repo_count: 6
github_show_profile_link: true
github_skip_forks: true

# Google Analytics
google_analytics_tracking_id: UA-11151622-1
